version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
    depends_on:
      - rabbitmq
      - redis
      - identity-service
      - media-service
      - post-service
      - search-service
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - IDENTITY_SERVICE_URL=http://identity-service:3001
      - POST_SERVICE_URL=http://post-service:3002
      - MEDIA_SERVICE_URL=http://media-service:3003
      - SEARCH_SERVICE_URL=http://search-service:3004

  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    env_file: ./identity-service/.env
    depends_on:
      - rabbitmq
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT=3001

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    env_file: ./post-service/.env
    depends_on:
      - rabbitmq
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT=3002

  media-service:
    build:
      context: ./media-service
      dockerfile: Dockerfile
    env_file: ./media-service/.env
    depends_on:
      - rabbitmq
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT=3003

  search-service:
    build:
      context: ./search-service
      dockerfile: Dockerfile
    env_file: ./search-service/.env
    depends_on:
      - rabbitmq
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT=3004

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
